repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        name: black (python formatter)
        language_version: python3.11
        additional_dependencies: []
        exclude: |
          ^app/|^packages/backend/.+\.ipynb$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8 (python lint)
        additional_dependencies: []
        args: ["--config=.flake8"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        name: remove unused noqa comments

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        args: ["-d", "{extends: default, rules: {line-length: disable}}"]
